---
language: ruby
rvm:
  - 2.3.0
  - 2.2.4
  - 2.1
  - jruby-9.0.4.0
  - jruby-head
  - ruby-head
  - rbx-2
matrix:
  exclude:
    - rvm: 2.1
      gemfile: gemfiles/rack_2.gemfile
  allow_failures:
    - rvm: rbx-2
    - rvm: jruby-head
    - rvm: ruby-head
gemfile:
  - gemfiles/rack_1.6.gemfile
  - gemfiles/rack_2.gemfile
before_script:
  - |
    case "${TRAVIS_RUBY_VERSION}" in
      rbx*)
        gem install psych
        ;;
    esac
  - rake travis:before -t
script: rake travis
after_script:
  - rake travis:after -t
sudo: false
