---
language: ruby
rvm:
  - 2.2.2
  - 2.1.6
  - 2.0.0
  - 1.9.3
  - jruby-1.7
  - jruby-9.0.0.0
  - jruby-head
  - ruby-head
  - rbx-2
matrix:
  allow_failures:
    - rvm: rbx-2
    - rvm: jruby-head
    - rvm: ruby-head
gemfile:
  - Gemfile
before_script:
  - |
    case "${TRAVIS_RUBY_VERSION}" in
      rbx*)
        gem install psych
        ;;
    esac
  - rake travis:before -t
script: rake travis
after_script:
  - rake travis:after -t
notifications:
  email:
    recipients:
      - FIX@example.com
    on_success: change
    on_failure: always
sudo: false
